### ISSUE TITLE
2021 한이음 공모전 신청

### ISSUE THREAD

**Issue by ShimWooJeong** [ShimWooJeong/AR_experiment#10]
개발보고서와 제작설계서 업로드 했습니다! 
30일까지 신청이어서 일요일 자정 전까지 피드백 주시면 감사하겠습니다(〃⌒▽⌒〃)ゝ
[보고서](https://github.com/ShimWooJeong/AR_experiment/tree/main/보고서)
+) 그리고 개발보고서 맨 첫 장은 컨펌 받은 후 전체적인 내용 기반으로 요약해 작성한 후 최종 완성해서 제출하겠습니다!

**Comment by jongfeel** [comment]
제가 토요일 오후에 보긴 했는데 코멘트를 이제서야 다네요.
작성하신 내용 대로 제출하면 될 거 같습니다.

### 보고서

보고서 첫장, 두번째 장은 얘기하신 대로 요약 작성한 후 제출해야 할 것 같습니다.
그리고 맨 마지막 장도 SW 제작 설계서 페이지라 삭제해야 할거 같아요.

### SW 제작 설계서

SW 제작 설계서의 경우 아래 페이지 수정 예정이신 것 같은데 꼭 확인하고 제출해야 할 것 같습니다.

- 22페이지 '추가해야댐-언니장면' 요기 잊지 마시고요
- 38페이지 '스마트폰 빌드 사진 추가' 요기도 잊지 말고 바꾸셔야 합니다.

마지막으로 형상관리의 경우는 한이음에서는 gitlab을 권장하고 있으므로 gitlab 쪽에 소스 올려서 관리하고 있다고 하는게 좋을 것 같습니다.
시간이 안되시면 그냥 해도 될 거 같아요 거기 까지는 한이음 측에서 확인을 안할수도 있으니까요.
그래도 다음 보고서에는 형상관리 스크린샷은 gitlab으로 바꾸면 좋을 것 같습니다.

**Comment by ShimWooJeong** [comment]
[공모전 신청 최종 제출물](https://github.com/ShimWooJeong/AR_experiment/tree/main/보고서)
물론 잊지 않고 "제작 설계서 사진 추가/개발 보고서 사진 추가 및 양식에 맞춰 다듬기"한 후에 위 결과물로 최종 제출했습니다!!
GitLab에 저희 파일들을 올리려고 했는데 터미널에서 자꾸 rejected 오류가 나면서 push가 안 되더라고요...
일단 한시가 급하니까 제출했고, 다음 제출부터는 GitLab으로 수정하도록 하겠습니다!
그리고 이번주 내로 미팅 날짜 잡아서 연락드리겠습니다! 월요팅 하세욥!!(--)(__)
