### ISSUE TITLE
#일주일 개발 목표 설정

### ISSUE THREAD

**Issue by ShimWooJeong** [ShimWooJeong/AR_experiment#11]
## 매주 화/수 연구실 출석해서 다같이 개발하는 시간 가지기
+ 수요일에는 우리끼리 회의시간(진행상황 공유, 개발 일정, 교수님 회의 전 내용 다듬기 등)
+ 수요일마다 일주일의 시간동안 개발할 목표 설정하여 코멘트 달기!
ex) 다음 회의 때까지 콩알탄 실험 씬 완성해오기, 불꽃반응실험 전체적으로 다듬어오기 등등

**Comment by ellen310** [comment]
2021.09.01~2021.09.08
1. raycast 등 사용하여 철저히 그 물체의 터치만 감지하도록 하기 (LeanTouch쪽을 더 섬세하게?)
2. 터치할때마다 ar위치 바뀌는 문제. groundPlane내부적 설정문제(?)고치기
3. 팝업창 ui디자인 변경

**Comment by jongfeel** [comment]
우와

여러분들 slack 쓰는 걸로 알고 있는데 갑자기 github가 활성화 되니 좋군요

**Comment by ShimWooJeong** [comment]
9월 1주차
- 불꽃반응실험 하나의 프리팹화
- SelectMaterial, SelectReagent 씬 VR화하기
- SelectMaterial 스크립트 수정

**Comment by jongfeel** [comment]
제가 github 꿀팁 또 알려드리겠습니다.

여러분이 작성한 글을 수정해서 task list로 만들어 드릴께요

**Comment by jongfeel** [comment]
내친 김에 내일 멘토링 하는 시간에 task 관리하는 걸 조금 더 도와드릴께요

**Comment by ShimWooJeong** [comment]
대박 지금 확인했는데 task list 이거 왕 좋네요!?
MBTI J 계획형인 저한테 정말 유용한 꿀팁입니다.. 멘토님 덕분에 앞으로 깃허브를 더 다양한 방면으로 사용하게 될 것 같아요🥺

**Comment by ShimWooJeong** [comment]
9월 2주차

- [ ] 콩알탄 게임 VR포팅 (던지는 느낌을 어떻게.. 잘 살려보기, 안 되면 총같은 걸로 해도 괜찮을지도)
- [ ] 불꽃반응실험의 배경입히기(HDRP의 Material 문제를 해결해야 함)

**Comment by ellen310** [comment]
9월 2주차

- [ ] 콩알탄 실험, 시뮬레이션게임 확인 후 현재 환경에 맞게 다듬기
- [ ] 콩알탄 실험, 시뮬레이션게임 GroundPlane에 배치하고 크기, 색상, 버튼 등 다듬기
- [ ] 효과음 추가하기
- [ ] 선택하기 부분 미리보기에 콩알탄, 시뮬레이션 게임 넣기

**Comment by Yanghaeun716** [comment]
콩알탄 실험 마무리 (터치에서 드래그로)
게임 진행 꾸며놓은 게임장 던지기 구현하기

**Comment by jongfeel** [comment]
하나의 issue에 계속 comment로 달면 스크롤 내리면서 보기 힘들어질겁니다.

각자 별도의 issue로 만들고 이걸 하나의 milestone으로 합쳐서 관리하면 조금 더 좋을 것 같습니다.

혹시 내일 모각코 들어오시는 분 있으면 모각코 끝나고 바로 설정해봐도 좋을 것 같군요.

**Comment by ShimWooJeong** [comment]
내일 저 모각코 참여합니다!
그럼 모각코 끝나고 한 번 설정 해보겠습니다..!

**Comment by jongfeel** [comment]
제가 알려드리면서 하면 좋을 거 같다는 얘기였어요. 하라고 시킨거 아닙니다 ㅋㅋㅋ

**Comment by jongfeel** [comment]
### To do

- Transfer `task` to `issue`
- Milestone

**Comment by mhjoon99** [comment]
- [ ] 콩알탄 게임 다듬기
- [ ] 태양계 게임 공전/자전 버튼으로 장면 전환 기능 추가
