### ISSUE TITLE
Unity HDRP Material 마젠타 문제 질문드립니다!

### ISSUE THREAD

**Issue by ShimWooJeong** [ShimWooJeong/AR_experiment#12]
불꽃반응실험을 어느정도 VR포팅을 완료한 후에 배경과 실험실 책상 등을 넣으려고 하고 있습니다.
[실험교실](https://assetstore.unity.com/packages/3d/environments/industrial/chemistry-laboratory-188274)  
저희가 구매한 VR 바탕으로 할 에셋인데요. HDRP로 지원을 하는 것 같아서 진행 중이던 프로젝트에 HDRP를 install 했더니 모든 Material이 마젠타 색으로 나오더라구요..ㅠ 구글에 서치해서  
Edit>Render Pipeline>HD Render Pipeline>Upgrade ... 이런 식으로 시도해봐도 마찬가지고..  
 Shader를 Standard거나 다른 에셋이름으로 되어 있던 걸 HDRP>Lit이나 Unlit으로 설정해줘도 원래의 Material으로는 안 나오고 대부분 흰색이거나 검정색처럼 나오더라구요
애초에 HDRP는 원래 사용하던 Material을 지원하지 않으니 되돌릴 순 없는 건가요?? 어흑흑.. 휴가 중이신 건 알지만 도저히 Shader나 Render 이런 부분은 잘 모르겠어서 질문 드려봅니다..!!
![캡처](https://user-images.githubusercontent.com/70475213/132338774-7e22e8c3-f02a-4ed8-bb70-6ca3900a7777.PNG)
사진은 원래 투명색인 Material 이구요. 카톡으로 보내주신 영상을 보셨으면 아시겠지만 원래 저런 색들이 아예 아닌데..~ 완전 어두컴컴 그 자체더라구요...

**Comment by jongfeel** [comment]
안녕하세요. 메일 보긴 했는데 도저히 댓글 쓸 시간을 못내서 집에 돌아오고 나서 잠깐 누운 뒤에 다시 일어나서 씁니다.

HDRP 에셋이라 뭔가 shader가 충돌이 나는 것 같네요??
기존 에셋들의 shader를 원래 쓰던 걸로 설정하면 되돌아 오긴 하는데, 잘 안되는 모양인 것 같습니다.

음
쉬운 방법으로 HDRP 에셋 가져오기 전 버전으로 되돌려 놓고
HDRP 지원하는 에셋을 별도의 unity project에서 설정해 보고 잘 되면 가져오는 방법으로 하는게 좋긴 합니다.

글 올린지 3일이나 지났는데 어떻게 진행하셨는지도 궁금하네요?

**Comment by ShimWooJeong** [comment]
이틀간을 HDRP 관련해서 시도하다가 시간이 넘 아까워서요ㅜㅠ.. 다른 일 먼저 진행 중이었답니다..
일단 불꽃반응실험 VR포팅 완성한 상태구요(최종완성이라기보단.. 베타느낌?) 그 이후 시간은 두 번째 콩알탄 실험 VR포팅 진행 중입니다! 그래도 이제 대략.. 전보다는 감을 잡아서 VR 포팅 시간을 단축할 수 있을 것 같아 다행이에요..~!!ㅠ
콩알탄 실험까지 VR포팅 마친 후 다시 한 번 HDRP 입히는 거 시도해보겠습니다! (HDRP는 실험실 배경, 책상을 위해서 쓰이는 거라 실험 두 개 완성해놓고 시도해도 될 것 같아서요!)
