### ISSUE TITLE
질문 #1

### ISSUE THREAD

**Issue by ShimWooJeong** [ShimWooJeong/AR_experiment#3]
멘토님 저희가 각자 노트북에서 만든 씬을 이제 하나로 합치려고 합니다!
근데 각자 만든 걸 합칠 수 있는 그런 방법이 있을까요???

**Comment by jongfeel** [comment]
밤새서 작업하셨다는 얘기에 일단 한번 놀라고
그걸 하루만에 하셨다는 것도 놀라웠습니다.

제가 지난 회의 때 prefab을 사용하는 방법을 알려 드렸으니
prefab에 대해 찾아 보시고 적용해 보면 좋을 것 같습니다.
