### ISSUE TITLE
VR배경 넣기

### ISSUE THREAD

**Issue by ShimWooJeong** [ShimWooJeong/AR_experiment#53]

**Comment by ShimWooJeong** [comment]
hdrp에 배경실 패키지를 넣고 거기에 우리 프리팹을 넣어보는 거 시도 -> 여전히 Material이 마젠타

**Comment by ShimWooJeong** [comment]
1. https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@7.1/manual/Upgrading-To-HDRP.html
-> 3d -> hdrp converting 하는 거 시도
2. hdrp를 3d로 downgrade(?) 하는 방법도 시도해보기

**Comment by jongfeel** [comment]
집에 가는 기차 안에서도 한이음을 해야 한다는 굳은 의지, 감동입니다!

**Comment by ShimWooJeong** [comment]
ㅋㅋㅋㅋㅋㅋ기록이 중요하다는 걸 많이 느꼈습니다!!

**Comment by ShimWooJeong** [comment]
> * https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@7.1/manual/Upgrading-To-HDRP.html
>   -> 3d -> hdrp converting 하는 거 시도
> * hdrp를 3d로 downgrade(?) 하는 방법도 시도해보기

HDRP를 기존 3D 프로젝트에 Import한 뒤에
Edit> Lender Pipeline> Upgrade Project Materials... (프로젝트 내에 있는 Material 중 HDRP로 업그레이드 가능한 것들 모두 업그레이드 하는?)
이후에도 마젠타 뜨는 Material들을 하나하나 HDRP->Lit 또는 Material에 적용되는 Texture를 찾아서 입혀주거나, 
Selected Material Upgrade... 하는 등의 조취를 취해서 어느정도 복구를 성공함 (물론 기존의 것과 완전히 같아 보이지는 않았지만)

그 후에 빌드를 하려고 할 때, PipeLine과 GLES3?가 충돌이 나고 Vulkan을 쓰라고 되어 있길래 그렇게 조취를 취해도 되지 않음(무슨 API가 호환이 안되는 듯한?)
기존에 진행해왔던 프로젝트의 빌드 환경설정과 같게 설정하면 오류가 나고 빌드가 되지 않아 오류대로 해결하다 검색 도중 HDRP는 Android에 지원을 하지 않는다는 글을 보게 되어(좀 더 알아보아야 할 듯) 일단은 2차 평가를 위해 다른 방법을 강구함

우리가 사용하려는 에셋에서 실험실이 만들어져있는 Prefab을 Export한 후에 우리 기존 3D 프로젝트에 Importing함(3D Object와 Material만 가져오는!)
전부 마젠타가 뜨는 것은 각 Matrial들의 Shader를 HDRP에서 Standard로 바꿔주니 잘 돌아옴

확실히 HDRP 환경에서보다 Fog와 특유의 부드럽고 따뜻한 분위기는 없지만 그래도 일단 실험실을 3D Object들로 구성할 수 있음에 만족!

**Comment by jongfeel** [comment]
우와
스크린샷 하나 추가해 주시면 좋을 것 같습니다!
