### ISSUE TITLE
VR콩알탄 게임 제작

### ISSUE THREAD

**Issue by ShimWooJeong** [ShimWooJeong/AR_experiment#59]

**Comment by ShimWooJeong** [comment]
[진행 사항](https://github.com/ShimWooJeong/AR_experiment/commit/4722f7c63e5daca6b1b4888fba5d319d807f6927)
- 
- 기존 실험실 공간을 활용해 게임장으로 구현
- Throw Object를 AddForce하는 방식은 그대로, 대신 Random.Range를 사용해 x값과 y값을 랜덤값으로 설정해서 오브젝트들이 랜덤하게 날아가도록 함
- Powder(반응물)을 맞추면 폭발을 일으키며 powder가 setfalse됨
- Throw Obect들은 Powder가 붙어있는 판에 충돌되면 setfalse됨과 동시에 AddForce 초기화 시켜주고, IsKinetic false해준 다음 원래 위치로 돌아가면서 settrue해줌

## 추가할 내용
- [ ] 점수 기능
- [ ] 타이머 기능
- [x] 우주게임처럼 로딩화면 추가하기(게임기 배치하는 중... 이런 식으로)
- [x] MainScene이랑 연결하기(로딩화면 통해서)
- [x] 게임장 안에도 Canvas로 게임 설명화면 띄우고 시작하기 눌러야 시작하도록 구현

**Comment by bamjun** [comment]
콩알탄 게임 언제 할수있나요 ?

**Comment by ShimWooJeong** [comment]
> 콩알탄 게임 언제 할수있나요 ?

ㅋㅋㅋㅋ범준님 제 깃허브 염탐하셨군요 콩알탄 게임 제작 되었답니다^^
