### ISSUE TITLE
SteamVR 설치 시 오류 발생 - Error during OpenVR Init: Init_PathRegistryNotFound

### ISSUE THREAD

**Issue by ellen310** [ShimWooJeong/AR_experiment#6]
멘토님 SteamVR 사용 중에 질문이 있습니다.
시험삼아 Oculus Integration으로 먼저 시도해보니 카메라 등이 안맞아서, 말씀 주셨던대로 이런 부분이 지원되는 SteamVR을 사용하기로 했습니다.

그런데 세팅을 다 마치고(steamVR plugin import, android switch platform등..) 오큘러스 퀘스트에 Build and Run 해보니 아래와 같은 오류가 발생했습니다. 구글링을 해봤는데도 잘 모르겠어서 질문드립니다.

![image](https://user-images.githubusercontent.com/70474886/126358540-38b44787-194b-4327-a29e-b888c83ad332.png)

**Comment by jongfeel** [comment]
우선 steam 설치 부터 해보면 어떨까요? path registry not found가 왠지 steam과 연동되어야 하는 path가 있는데 못찾는거 같아서요.

**Comment by ellen310** [comment]
그래서 어제 steam도 설치해서 이것저것 해봤는데 생각처럼 안되더라구요ㅠ 우선 path부분을 다시 한번 확인 해 보겠습니다! 감사합니다.

**Comment by jongfeel** [comment]
그리고 다른 얘기인데...

질문에 대한 제목을 질문으로 하면 내용을 클릭해서 들어와 봐야 알 수 있으니 `제목`이라는 의미에 충실하게 요약 내용을 적어보면 좋을 것 같습니다.

제가 예시로 수정해서 적어 볼께요.

**Comment by ellen310** [comment]
아하 넵 다음부터 참고해서 작성하도록 하겠습니다!

**Comment by jongfeel** [comment]
이거 해결이 된건가요?
어떻게 해결했는지 알려주세요

**Comment by ellen310** [comment]
아직 해결 안됐고, 미리 테스트 해본 Oculus Integration은 그나마 되어서 이걸로 포팅 진행하고 있습니다.

**Comment by ellen310** [comment]
그런데 곧 해결할 수 있을 것 같습니다..!!!!! 해결되면 말씀 드릴게요!!!
