### ISSUE TITLE
Oculus HandTracking 손 방향 문제

### ISSUE THREAD

**Issue by ShimWooJeong** [ShimWooJeong/AR_experiment#9]
핸드트래킹 빌드 성공 이후 오브젝트 잡는 것까지 시도해보고 프로젝트에 적용하는 중입니다!
그런데 오브젝트를 잡을 때 정확히 손가락쪽의 방향으로 잡는 것이 아닌 손날(그러니까 새끼손가락쪽)의 방향에 오브젝트를 두게 한 후에 잡아야지 잡힙니다
![질문](https://user-images.githubusercontent.com/70475213/130355780-46e4d09b-e695-43c8-b2ee-902c3d0d332d.PNG)

글로는 이해하기 어려우실까봐 급하게 그림판으로 그려봤습니다..ㅠㅠ 왼쪽처럼 손을 정방향으로 해놓고 잡으려고 하면 잡히지 않고 오른쪽처럼 손날방향으로 해야 오브젝트가 잡힙니다
OVRCameraRig/TrackingSpace/RightHandAnchor와 LeftHandAnchor가 각각 오른손, 왼손인데 Collider를 옮겨보기도 하고, 오브젝트의 Collider를 옮겨보기도 했지만 똑같더라구요
제 생각에는 아래 그림처럼 검정색이 제 손이며, VR상에서 보이는 손이라면 실제 오브젝트와 상호작용할 수 있는? 그런 인식은 하늘색 부분인 건 아닐지.. 그래서 RightHandAnchor와 LeftHandAnchor의 Rotation을 바꿔봤지만 똑같더라구요.. (근데 다른 씬을 새로 제작해서 똑같이 시도해보던 중 똑같이 저런 손날 방향으로 잡히다가 RightHandAnchor와 LeftHandAnchor의 Rotation을 270으로 바꾸니까 정방향으로 잘 되던데.. 똑같이 원래 하던 씬에 적용하니까 안 됩니다..ㅠㅠ)
참고했던 유튜브 영상도 혹시 몰라 첨부합니다 완전 똑같이 했는데도... 저렇게 안 되더라구요...
어떻게 하면 손을 정확하게 상호작용할 수 있도록 인식할 수 있을까요ㅠㅠ?
만약 이해하시기 어려우시다면 한이음 공모전 보고서 얘기할 겸 회의를 잡고 회의시간에 질문하도록 하겠습니다!

말씀드린 씬은 이 파일입니다!
https://github.com/ShimWooJeong/AR_experiment/commit/789c5aa1ab8c7d50acbc7e84fdf2b24477a772cb

**Comment by jongfeel** [comment]
회의 때 한번 보는게 좋을 것 같네요.

유튜브 영상 링크는 없는데 다시 추가해볼 수 있을까요?

**Comment by ShimWooJeong** [comment]
https://www.youtube.com/watch?v=UoSzhoZ18bE
위 링크입니다! 그럼 팀원들이랑 회의 날짜 잡고 말씀드릴게욥
